version: '3'
services:
  web:
    image: php:7.4-apache
    container_name: web-server
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./db:/home/db
    depends_on:
      - db

  db:
    image: alpine
    container_name: sqlite
    volumes:
      - ./db:/var/lib/sqlite
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"
